### Get category list by anon
GET http://127.0.0.1:8000/api/v1/categories HTTP/1.1
Content-Type: application/json

### Create a category by anon [Forbidden]
POST http://127.0.0.1:8000/api/v1/categories/ HTTP/1.1
Content-Type: application/json

{
    "name": "category_001",
    "slug": "category_001"
}

### Delete a category by anon [Forbidden]
DELETE http://127.0.0.1:8000/api/v1/categories/category_001/ HTTP/1.1
Content-Type: application/json

##########################################################################################
### Get genre list by anon
GET http://127.0.0.1:8000/api/v1/genres HTTP/1.1
Content-Type: application/json

### Create a genre by anon [Forbidden]
POST http://127.0.0.1:8000/api/v1/genres/ HTTP/1.1
Content-Type: application/json

{
    "name": "genre_001",
    "slug": "genre_001"
}

### Delete a genre by anon [Forbidden]
DELETE http://127.0.0.1:8000/api/v1/genres/genre_001/ HTTP/1.1
Content-Type: application/json

##########################################################################################
### Get title list by anon
GET http://127.0.0.1:8000/api/v1/titles/ HTTP/1.1
Content-Type: application/json

### Get title by id by anon
GET http://127.0.0.1:8000/api/v1/titles/1/ HTTP/1.1
Content-Type: application/json

### Create a title by anon [Forbidden]
POST http://127.0.0.1:8000/api/v1/titles/ HTTP/1.1
Content-Type: application/json

{
  "name": "Test_name_01",
  "year": 2024,
  "description": "Test_description_01",
  "genre": [
    "fantasy",
    "comedy"
  ],
  "category": "book"
}

### Update a title by anon [Forbidden]
PATCH http://127.0.0.1:8000/api/v1/titles/9/ HTTP/1.1
Content-Type: application/json

{
  "name": "Test_name_03",
  "year": 2024,
  "description": "Test_description_01",
  "genre": [
    "fantasy",
    "comedy"
  ],
  "category": "music"
}

### Delete a title by anon [Forbidden]
DELETE http://127.0.0.1:8000/api/v1/titles/9/ HTTP/1.1
Content-Type: application/json
