# Generated by Django 3.2 on 2024-11-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_bio'),
        ('users', '0006_alter_customuser_username'),
    ]

    operations = [
    ]
