# Generated by Django 3.2 on 2024-10-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug', 'name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['slug', 'name']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-year', 'category', 'name']},
        ),
    ]
